### ISSUE TITLE
Reroute points not dragged

### ISSUE THREAD

**Issue by fdtdev** [Siccity/xNodeGroups#2]
Reroute points in handles are not dragged by the Group.

**Comment by fdtdev** [comment]
Maybe the reroute points structure could save the number assigned to draw handle to access it later from the group editor ? for that to work, xnode should be modified to include nodegroup as part of the engine instead of an addon.

**Comment by Siccity** [comment]
296c49d9048cd074037760af7f19c58ad8261c4b Fixed :)
